import os
import ipaddress
from datetime import datetime

import requests
import urllib3
from dotenv import load_dotenv

# Suppress warnings about self-signed certificate (fine for lab use only)
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

# Load AbuseIPDB API key from .env
load_dotenv()
ABUSEIPDB_API_KEY = os.getenv("ABUSEIPDB_API_KEY")

# --- Configuration ---
INDEXER_URL = "https://localhost:9200"
USERNAME = os.getenv("WAZUH_USERNAME")
PASSWORD = os.getenv("WAZUH_PASSWORD")


def fetch_bruteforce_alert():
    """Fetch the main SSH brute-force alert (rule 40112) from Wazuh."""
    query = {
        "query": {
            "match": {
                "rule.id": "40112"
            }
        },
        "sort": [
            {"timestamp": {"order": "asc"}}
        ]
    }

    response = requests.get(
        f"{INDEXER_URL}/wazuh-alerts-*/_search",
        auth=(USERNAME, PASSWORD),
        json=query,
        verify=False
    )

    response.raise_for_status()
    return response.json()


def check_ip_reputation(ip):
    """Check an IP against AbuseIPDB, handling private/internal IPs gracefully."""
    try:
        if ipaddress.ip_address(ip).is_private:
            return {
                "status": "internal",
                "message": f"{ip} is a private/internal lab IP — no public threat intel applies."
            }
    except ValueError:
        return {"status": "error", "message": f"Invalid IP: {ip}"}

    url = "https://api.abuseipdb.com/api/v2/check"
    headers = {
        "Key": ABUSEIPDB_API_KEY,
        "Accept": "application/json"
    }
    params = {"ipAddress": ip, "maxAgeInDays": 90}

    response = requests.get(url, headers=headers, params=params)

    if response.status_code != 200:
        return {"status": "error", "message": f"API error: {response.status_code}"}

    data = response.json()["data"]
    return {
        "status": "public",
        "abuse_score": data.get("abuseConfidenceScore"),
        "country": data.get("countryCode"),
        "isp": data.get("isp"),
        "total_reports": data.get("totalReports")
    }


def generate_report(alert):
    """Build a Markdown incident report string from one alert's data."""
    rule = alert["rule"]
    details = alert["data"]
    src_ip = details.get("srcip")

    reputation = check_ip_reputation(src_ip)

    if reputation["status"] == "internal":
        threat_intel_section = reputation["message"]
    elif reputation["status"] == "error":
        threat_intel_section = f"Could not retrieve threat intelligence: {reputation['message']}"
    else:
        threat_intel_section = f"""- **Abuse Confidence Score:** {reputation['abuse_score']}/100
- **Country:** {reputation['country']}
- **ISP/Provider:** {reputation['isp']}
- **Total Abuse Reports:** {reputation['total_reports']}"""

    report = f"""# Incident Report: SSH Brute-Force Login (Auto-Generated)

## Incident Summary
A brute-force SSH login attack was detected against agent 
`{alert.get("agent", {}).get("name")}`, targeting user account 
`{details.get("dstuser")}`. Wazuh correlated multiple authentication 
failures followed by a successful login.

## Detection Details
- **Timestamp:** {alert.get("timestamp")}
- **Rule ID:** {rule.get("id")}
- **Rule Level:** {rule.get("level")}
- **Rule Description:** {rule.get("description")}
- **Correlated Failures Before Success (rule.frequency):** {rule.get("frequency")}

## Source of Attack
- **Source IP:** {src_ip}
- **Source Port:** {details.get("srcport")}

## Target
- **Agent:** {alert.get("agent", {}).get("name")}
- **Targeted Account:** {details.get("dstuser")}

## Threat Intelligence
{threat_intel_section}

## MITRE ATT&CK Mapping
- **Techniques:** {", ".join(rule.get("mitre", {}).get("technique", []))}
- **Tactics:** {", ".join(rule.get("mitre", {}).get("tactic", []))}

## Recommendation
- Enforce strong password policy for all accounts
- Enable SSH key-based authentication and disable password login
- Implement fail2ban or similar to auto-block repeated failed login sources
- Enable multi-factor authentication where possible

---
*This report was automatically generated by fetch_alerts.py at 
{datetime.now().isoformat()}.*
"""
    return report


def save_report(report_text, filename="reports/auto-generated-draft-report.md"):
    with open(filename, "w", encoding="utf-8") as f:
        f.write(report_text)
    print(f"Report saved to: {filename}")


def main():
    data = fetch_bruteforce_alert()
    total_hits = data["hits"]["total"]["value"]
    print("Total matching alerts:", total_hits)

    if total_hits == 0:
        print("No brute-force alerts found.")
        return

    alert = data["hits"]["hits"][0]["_source"]
    report_text = generate_report(alert)
    save_report(report_text)


if __name__ == "__main__":
    main()